Repository NAD777/codetest_bot, pull requests merged in 2023-05, with the labels that each got.

#4 Bot
  .gitignore
  bot/Dockerfile
  bot/build.gradle.kts
  bot/settings.gradle.kts
  bot/src/main/java/com/github/nad777/bot/BotApplication.java
  bot/src/main/java/com/github/nad777/bot/client/JugglerClient.java
  bot/src/main/java/com/github/nad777/bot/client/requests/SubmitTaskRequest.java
  bot/src/main/java/com/github/nad777/bot/client/responses/ListTasksResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/SubmitTaskResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/TaskFileResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/TaskResponse.java
  bot/src/main/java/com/github/nad777/bot/configuration/ApplicationConfig.java
  bot/src/main/java/com/github/nad777/bot/configuration/BotConfiguration.java
  bot/src/main/java/com/github/nad777/bot/configuration/ClientConfiguration.java
  bot/src/main/java/com/github/nad777/bot/controller/BotController.java
  bot/src/main/java/com/github/nad777/bot/controller/ExceptionApiHandler.java
  bot/src/main/java/com/github/nad777/bot/controller/requests/ResultUpdateRequest.java
  bot/src/main/java/com/github/nad777/bot/controller/responses/ApiErrorResponse.java
  bot/src/main/java/com/github/nad777/bot/core/Bot.java
  bot/src/main/java/com/github/nad777/bot/core/State.java
  bot/src/main/java/com/github/nad777/bot/core/UserMessageProcessor.java
  bot/src/main/java/com/github/nad777/bot/core/commands/Command.java
  bot/src/main/java/com/github/nad777/bot/core/commands/HelpCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/ListCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/StartCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/StopCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/TaskCommand.java
  bot/src/main/resources/application.properties
  bot/src/test/java/com/github/nad777/bot/BotApplicationTests.java
  docker-compose.yaml
Labels: enhancement

#5 Orchestrator
  .gitignore
  LICENSE
  configs/compiler_config.yaml
  configs/solution_config.yaml
  docker-compose.yaml
  orchestrator/orchestrator/Dockerfile
  orchestrator/orchestrator/app.py
  orchestrator/orchestrator/manual_tests/Main.java
  orchestrator/orchestrator/manual_tests/invalid.py
  orchestrator/orchestrator/manual_tests/test.py
  orchestrator/orchestrator/manual_tests/valid.py
  orchestrator/orchestrator/test_runner.py
  orchestrator/runners/Dockerfile
  orchestrator/runners/run.sh
  orchestrator/runners/runner.py
  problem_set/README
  problem_set/master_solutions/Solution.java
  problem_set/master_solutions/solution.py
  problem_set/master_solutions/task_1.py
Labels: enhancement

#7 Hotfix
  bot/src/main/java/com/github/nad777/bot/client/JugglerClient.java
  bot/src/main/java/com/github/nad777/bot/client/requests/SubmitTaskRequest.java
  bot/src/main/java/com/github/nad777/bot/client/responses/ListTasksResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/SubmitTaskResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/TaskFileResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/TaskResponse.java
  bot/src/main/java/com/github/nad777/bot/controller/BotController.java
  bot/src/main/java/com/github/nad777/bot/controller/requests/ResultUpdateRequest.java
  bot/src/main/java/com/github/nad777/bot/core/Bot.java
  bot/src/main/java/com/github/nad777/bot/core/MarkdownProcessor.java
  bot/src/main/java/com/github/nad777/bot/core/UserMessageProcessor.java
  bot/src/main/java/com/github/nad777/bot/core/commands/HelpCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/ListCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/StartCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/StopCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/TaskCommand.java
  bot/src/main/resources/application.properties
  configs/compiler_config.yaml
  docker-compose.yaml
  juggler/Dockerfile
  juggler/app.py
  orchestrator/orchestrator/Dockerfile
  orchestrator/orchestrator/app.py
  orchestrator/orchestrator/test_runner.py
  orchestrator/runners/Dockerfile
  orchestrator/runners/runner.py
Labels: bug

#8 Orchestrator
  configs/compiler_config.yaml
  configs/solution_config.yaml
  docker-compose.yaml
  juggler/app.py
  juggler/master_solutions/run.sh
  orchestrator/orchestrator/Dockerfile
  orchestrator/orchestrator/app.py
  orchestrator/orchestrator/test_runner.py
  orchestrator/runners/Dockerfile
  orchestrator/runners/runner.py
  orchestrator/runners/test.sh
  problem_set/README
  problem_set/master_solutions/Solution.java
  problem_set/master_solutions/solution.py
  problem_set/master_solutions/task_1.py
Labels: bug, enhancement

#9 Bot
  .github/workflows/bot.yml
  .gitignore
  bot/Dockerfile
  bot/build.gradle.kts
  bot/checkstyle.xml
  bot/src/main/java/com/github/nad777/bot/BotApplication.java
  bot/src/main/java/com/github/nad777/bot/client/JugglerClient.java
  bot/src/main/java/com/github/nad777/bot/client/requests/AddTaskRequest.java
  bot/src/main/java/com/github/nad777/bot/client/requests/SubmitTaskRequest.java
  bot/src/main/java/com/github/nad777/bot/client/responses/AddTaskResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/SubmitTaskResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/TaskFileResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/TaskResponse.java
  bot/src/main/java/com/github/nad777/bot/controller/BotController.java
  bot/src/main/java/com/github/nad777/bot/controller/requests/ResultUpdateRequest.java
  bot/src/main/java/com/github/nad777/bot/core/Bot.java
  bot/src/main/java/com/github/nad777/bot/core/MarkdownProcessor.java
  bot/src/main/java/com/github/nad777/bot/core/State.java
  bot/src/main/java/com/github/nad777/bot/core/StateInfo.java
  bot/src/main/java/com/github/nad777/bot/core/UserMessageProcessor.java
  bot/src/main/java/com/github/nad777/bot/core/commands/AddTaskCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/Command.java
  bot/src/main/java/com/github/nad777/bot/core/commands/GetTaskCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/ListCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/SubmitCommand.java
  bot/src/main/resources/application.properties
  bot/src/test/java/com/github/nad777/bot/BotApplicationTests.java
  docker-compose.yaml
Labels: enhancement

#11 Combine features
  .github/workflows/bot.yml
  .github/workflows/juggler.yml
  .github/workflows/orchestrator.yml
  .github/workflows/runner.yml
  .gitignore
  bot/Dockerfile
  bot/build.gradle.kts
  bot/checkstyle.xml
  bot/src/main/java/com/github/nad777/bot/BotApplication.java
  bot/src/main/java/com/github/nad777/bot/client/JugglerClient.java
  bot/src/main/java/com/github/nad777/bot/client/requests/AddTaskRequest.java
  bot/src/main/java/com/github/nad777/bot/client/requests/SubmitTaskRequest.java
  bot/src/main/java/com/github/nad777/bot/client/responses/AddTaskResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/SubmitTaskResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/TaskFileResponse.java
  bot/src/main/java/com/github/nad777/bot/client/responses/TaskResponse.java
  bot/src/main/java/com/github/nad777/bot/controller/BotController.java
  bot/src/main/java/com/github/nad777/bot/controller/requests/ResultUpdateRequest.java
  bot/src/main/java/com/github/nad777/bot/core/Bot.java
  bot/src/main/java/com/github/nad777/bot/core/MarkdownProcessor.java
  bot/src/main/java/com/github/nad777/bot/core/State.java
  bot/src/main/java/com/github/nad777/bot/core/StateInfo.java
  bot/src/main/java/com/github/nad777/bot/core/UserMessageProcessor.java
  bot/src/main/java/com/github/nad777/bot/core/commands/AddTaskCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/Command.java
  bot/src/main/java/com/github/nad777/bot/core/commands/GetTaskCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/ListCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/StartCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/StopCommand.java
  bot/src/main/java/com/github/nad777/bot/core/commands/SubmitCommand.java
  bot/src/main/resources/application.properties
  bot/src/test/java/com/github/nad777/bot/BotApplicationTests.java
  configs/compiler_config.yaml
  configs/solution_config.yaml
  docker-compose.yaml
  juggler/app.py
  juggler/database/all_models.py
  juggler/database/db_session.py
  juggler/master_solutions/masterAPlusB.py
  juggler/master_solutions/run.sh
  orchestrator/orchestrator/Dockerfile
  orchestrator/orchestrator/app.py
  orchestrator/orchestrator/manual_tests/invalid.py
  orchestrator/orchestrator/manual_tests/test.py
  orchestrator/orchestrator/manual_tests/valid.py
  orchestrator/orchestrator/test_runner.py
  orchestrator/runners/Dockerfile
  orchestrator/runners/runner.py
  orchestrator/runners/test.sh
  problem_set/README
  problem_set/master_solutions/Solution.java
  problem_set/master_solutions/solution.py
  problem_set/master_solutions/task_1.py
Labels: enhancement

#12 Hotfix
  .github/workflows/bot.yml
  .github/workflows/juggler.yml
  .github/workflows/orchestrator.yml
  .github/workflows/runner.yml
  Postgres/Dockerfile
  Postgres/scripts/create_all.sql
  bot/src/main/java/com/github/nad777/bot/core/UserMessageProcessor.java
  docker-compose.yaml
Labels: bug

#14 Bot
  .gitignore
  bot/build.gradle.kts
  bot/src/main/java/com/github/nad777/bot/core/Bot.java
  bot/src/main/resources/application.properties
  configs/prometheus.yml
  docker-compose.yaml
Labels: enhancement
